default: &default
  adapter: mysql2
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  adapter: sqlite3
  database: nowatt_ember_development

test:
  <<: *default
  adapter: sqlite3
  database: nowatt_ember_test

production:
  <<: *default
  database: nowatt_ember_production
  username: nowatt_ember
  password: <%= ENV['NOWATT_EMBER_DATABASE_PASSWORD'] %>
