# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7979746266f37fd571408e3052dba953e531fb92e8eaae3406e7ef6ab745a3bf9070483591e2896c5343f06d61f8515743694dec4aadde8859b15d52b4d22566

test:
  secret_key_base: 89d8c61e7b01d861c3ef0088d8a8c08f3197c3f479bec67893a0a3ee2b7abadb3741082b119fa6e459ee9dedba0d38ada4cb50e29375c1fe43b2923227643088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
